const DATA_SOURCE = 'DATA_SOURCE';
const USER_REPOSITORY = 'USER_REPOSITORY';
const ROLE_REPOSITORY = 'ROLE_REPOSITORY';
const VEHICLE_REPOSITORY = 'VEHICLE_REPOSITORY';
const CHECKLIST_REPOSITORY = 'CHECKLIST_REPOSITORY';
const CHECKLIST_VEHICLE_REPOSITORY = 'CHECKLIST_VEHICLE_REPOSITORY';

export { CHECKLIST_REPOSITORY, CHECKLIST_VEHICLE_REPOSITORY, DATA_SOURCE, ROLE_REPOSITORY, USER_REPOSITORY, VEHICLE_REPOSITORY };

