const DATA_SOURCE = 'DATA_SOURCE';
const USUARIO_REPOSITORY = 'USUARIO_REPOSITORY';
const GRUPO_REPOSITORY = 'GRUPO_REPOSITORY';
const VEICULOS_REPOSITORY = 'VEICULOS_REPOSITORY';

export { DATA_SOURCE, GRUPO_REPOSITORY, USUARIO_REPOSITORY, VEICULOS_REPOSITORY };

