const DATA_SOURCE = 'DATA_SOURCE';
const USUARIO_REPOSITORY = 'USUARIO_REPOSITORY';
const VEICULOS_REPOSITORY = 'VEICULOS_REPOSITORY';

export { DATA_SOURCE, USUARIO_REPOSITORY, VEICULOS_REPOSITORY };
